### ISSUE TITLE
直方图loss 好像还有问题...

### ISSUE THREAD

**Issue by peachis** [Oldpan/Deep-Painterly-Harmonization-Pytorch#3]
从您的blog慕名而来，想学习一下直方图loss的计算方式... 可是发现您的代码里面这一块好像还有问题...

想咨询一下直方图loss的具体实现过程，看您是准备在hook中计算loss...这是为什么呢？

**Comment by Oldpan** [comment]
这个代码已经好久没有维护了，虽然能跑，但是占用的显存多达10G。
在hook中计算只是为了方便，放到别的地方也是可以的。
这个代码是参照torch版的官方修改来的，官方使用的是cuda代码写的直方图损失，我个人使用python写过但是速度太慢，最终还是采用了cuda代码，这个里头有的，可以运行

**Comment by peachis** [comment]
好的 谢谢您啦。
我自己改了一下使用了pytorch 的 histc方法替代了hist的计算，然后更改了您代码中用> 0.1这种方式取mask区域，改为通过gather的方法，就跟您在另外两个loss中的那样，这样一来hist loss就可以用了。

**Comment by SFidea** [comment]
> 好的 谢谢您啦。
> 我自己改了一下使用了pytorch 的 histc方法替代了hist的计算，然后更改了您代码中用> 0.1这种方式取mask区域，改为通过gather的方法，就跟您在另外两个loss中的那样，这样一来hist loss就可以用了。

可以分享下您的代码吗？非常感谢~

**Comment by lefiniti** [comment]
> 好的 谢谢您啦。
> 我自己改了一下使用了pytorch 的 histc方法替代了hist的计算，然后更改了您代码中用> 0.1这种方式取mask区域，改为通过gather的方法，就跟您在另外两个loss中的那样，这样一来hist loss就可以用了。

您好，请问可以分享一下您后来是怎么修改的吗？谢谢您，好人一生平安。

**Comment by peachis** [comment]
```python
def hist_loss(ori_feature, style_feature, mask_input, index):
    # 输入分别为：
    # ori_feature -- 输入特征，待匹配
    # style_feature -- 参考特征
    # mask_input -- mask标记图，与输入图同大小
    # index -- mask中需要匹配的区域的序号，一个list对应一张图

    loss = 0

    # sh = hist_mask(style_feature, mask_input)
    batch, channels, height, width = ori_feature.shape
    of = ori_feature.view(batch, channels, -1)
    sf = style_feature.view(batch, channels, -1)

    mask = mask_input.contiguous().view(batch, 1, -1)

    of_masked = of * mask # 求取mask区域的值
    sf_masked = sf * mask

    for bt in range(batch):
        # of_maskarea = torch.cat([of_masked[bt][i][mask[bt][0] >= 0.1].unsqueeze(0) for i in range(of_masked.size(1))])
        of_maskarea = of_masked[bt].gather(1, index[bt]) # 通过gather的方法可以减少计算量

        # style_hist = torch.cat([torch.histc(sf_masked[bt][i][mask[bt][0] >= 0.1].cpu(), N_BINS).unsqueeze(0) for i in range(sf_masked.size(1))]).cuda() # 求取参考区域的hist
        sf_maskedarea = sf_masked[bt].gather(1, index[bt]).cpu()
        style_hist = torch.cat([sf_maskedarea[i].histc(N_BINS).unsqueeze(0) for i in range(sf_masked.size(1))]).to(device) # 求取参考区域的hist

        remap = remap_hist(of_maskarea, style_hist) # 这里的remap用的就是版主的那个
        loss += F.mse_loss(of_maskarea, remap) # requires_grad=False mse_loss

    return loss / 2
```

我写了这个以后发现有个问题，就是当mask区域过大的时候会显示内存溢出，我的显卡是1070ti 8g，图像大小8*3*224*224。

需要注意的是，这个loss我没有应用在painterly这段代码中，而是使用在自己的工程里了。
推荐想用的同行们也可以参考版主提到的那个男人的主页，他用fast.ai实现了luan的工程，很厉害。
[Sylvain Gugger - Deep Painterly Harmonization](https://sgugger.github.io/deep-painterly-harmonization.html#deep-painterly-harmonization)

`**如果有谁完成了painterly的pytorch版的代码，还请告诉我，我一定麻溜的去加星并且关注。**`

**Comment by lefiniti** [comment]
万分感谢分享，我正在尝试painterly，回头给您反馈
